#!/usr/bin/env node

/*
 * cmd/flamegraph: emit a flame graph SVG from collapsed output
 */

var mod_bunyan = require('bunyan');
var mod_stackvis = require('../lib/stackvis');

var log = new mod_bunyan({
    'name': 'flamegraph',
    'stream': process.stderr
});

var reader = new mod_stackvis.readerLookup('collapsed');
var writer = new mod_stackvis.writerLookup('flamegraph-svg');

mod_stackvis.pipeStacks(log, process.stdin, reader, writer, process.stdout,
    function () {});
process.stdin.resume();
