#!/usr/bin/env node

/*
 * cmd/stackcollapse: emit collapsed stack traces from DTrace output
 */

var mod_input_common = require('../lib/input-common');
var mod_input_dtrace = require('../lib/input-dtrace');
var mod_bunyan = require('bunyan');

var log = new mod_bunyan({
    'name': 'stackcollapse',
    'stream': process.stderr
});

var reader = new mod_input_dtrace.reader(process.stdin, log);
mod_input_common.collapseStacks(reader, function (err, stacks) {
	stacks.eachStackSorted(function (frames, count) {
		process.stdout.write(frames.join(',') + ' ' + count + '\n');
	});
});

process.stdin.resume();
